// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2dgTaf2tTjxmGWeugCl-DrvAfobBKMI',
    appId: '1:347398125662:web:8b829571ca5ea4d9d21ccf',
    messagingSenderId: '347398125662',
    projectId: 'ruteandoback',
    authDomain: 'ruteandoback.firebaseapp.com',
    storageBucket: 'ruteandoback.firebasestorage.app',
    measurementId: 'G-7YFGEMZKCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm8rDWQNvgYb4VSyzOX5kMMh5xnN2M6hU',
    appId: '1:347398125662:android:c90e3b4b70440700d21ccf',
    messagingSenderId: '347398125662',
    projectId: 'ruteandoback',
    storageBucket: 'ruteandoback.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHmyy7cIyhFNzLANBSu0uGN1DqPPIDJAY',
    appId: '1:347398125662:ios:aed2916dfb34e73fd21ccf',
    messagingSenderId: '347398125662',
    projectId: 'ruteandoback',
    storageBucket: 'ruteandoback.firebasestorage.app',
    iosBundleId: 'com.example.ruteandoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2dgTaf2tTjxmGWeugCl-DrvAfobBKMI',
    appId: '1:347398125662:web:db99ab871c5f17a0d21ccf',
    messagingSenderId: '347398125662',
    projectId: 'ruteandoback',
    authDomain: 'ruteandoback.firebaseapp.com',
    storageBucket: 'ruteandoback.firebasestorage.app',
    measurementId: 'G-4KW1HDDHZZ',
  );
}
